services:
  backend:
    cap_add: 
      - SYS_PTRACE
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     memory: 2Gb
      #     cpus: '0.5'
      x-aws-autoscaling:
          min: 1
          max: 10 #required
          cpu: 75