name: Docker Compose CI CD to DockerHub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build and push backend
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: ./backend/Dockerfile
          push: true
          tag_with_sha: true
          tag_with_ref: true
      -
        name: Build and push proxy
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: ./proxy/Dockerfile
          push: true
          tag_with_sha: true
          tag_with_ref: true
